Create App structure and four components
IBTechRaj/ReactCalculator pull request #3
Opened 2020-06-02 16:31 UTC by IBTechRaj

- Created components folder
- Created four files in components folder and created basic Calculator project structure

Submitting for code review. 
Thanks

2020-06-03 13:26 UTC, shloch requested changes
## Hello @IBTechRaj , 

We're advancing well, good job so far with what you've brought up
But we have some debugging to do......... (see comments below)

### Happy coding

2020-06-03 13:26 UTC, shloch commented on src/components/Display.js
> +
- this component should have an incoming prop called `result` [see [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/incomingProps.png)]
- `result` should be a string (validate this with `propTypes`) [see [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/validateAsString.png)]

- `result` should have default value of `"0"` (enforce this with `defaultProps`) [see [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/DefaultProp.png)]

2020-06-03 13:26 UTC, shloch commented on src/components/Button.js
> +}
- this component should accept an incoming `name` prop [see [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/button/acceptProp.png)]

- `name` prop should be string (enforce this with `propTypes`) [see [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/button/validateAsString.png)]

2020-06-03 13:26 UTC, shloch commented on src/components/ButtonPanel.js
> +          </div>
From my comment above (regarding the `<Button />` component,

this implies, you should render `<Button />` component here and pass a `name` prop

2020-06-03 13:26 UTC, shloch commented on src/components/Button.js
> +}
It's advisable to not use the `React children` approach here........

2020-06-03 13:27 UTC, shloch commented
Also, fix any `Stickler` error that you have

2020-06-09 05:11 UTC, IBTechRaj commented
Made all the corrections suggested.

Submitting for rereview of code

2020-06-09 17:58 UTC, bellom approved these changes
## Hi @IBTechRaj  :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-06-17 11:34 UTC, merged