Milestone 4
IBTechRaj/ReactCalculator pull request #5
Opened 2020-06-07 15:48 UTC by IBTechRaj

Finished requirements of Milestone-4.
-This milestone is created from Milestone-3. I think, after approval, I have to merge with Milestone-3. Please advise.

Thanks

2020-06-09 16:22 UTC, Redvanisation requested changes
# Changes required  ♻️ 

### Hello team  🌟

**Nice work on this project, but the following changes need to be done before moving on ⬇️** 

- Nicely done however the linter should be passing, please fix that.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2020-06-18 16:50 UTC, IBTechRaj commented
Hi, I have fixed all linting errors and style error in local repo and pushed it. But here in Github I am finding the errors again. 

I need help. I am not able to connect with my reviewer. That is why requesting another code review.  

Thanks

2020-06-19 09:54 UTC, fatymahmed requested changes
### Hi @IBTechRaj,
- [ ] Make sure that linter checks are passing.

- The following is marked as `optional` because it was not mentioned in the first review but I highly suggest you to make the change

[OPTIONAL]
- The project should have a descriptive README.md [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from Pathwright
### Status: Changes Required ♻️
_Feel free to reach out to me on slack (Fatima), if you have any questions_

2020-06-19 09:56 UTC, fatymahmed commented
> Hi, I have fixed all linting errors and style error in local repo and pushed it. But here in Github I am finding the errors again.
> 
> I need help. I am not able to connect with my reviewer. That is why requesting another code review.
> 
> Thanks

Hi @IBTechRaj, I've reached out to you on slack regarding this.

2020-06-19 11:24 UTC, IBTechRaj commented
I have done all the corrections suggested. Also thanks for the help from Fatima Ahmed. 
Submitting for re-review.

2020-06-19 13:01 UTC, shloch approved these changes
## Hello @IBTechRaj 

### You get a thumbs,  but please we'll have to reject any submission with git-branch conflicts.

![Screen Shot 2020-06-19 at 1 58 15 PM](https://user-images.githubusercontent.com/40712459/85134302-2e1e4280-b234-11ea-9069-73a11ca435a4.png)

The base branch should be `development`, every other milestone-branch should branch out from `development`
![Screen Shot 2020-06-19 at 1 56 05 PM](https://user-images.githubusercontent.com/40712459/85134342-3c6c5e80-b234-11ea-95f1-71599045aeba.png)

Dont forget to re-read if need be [GIT-FLOW guideline](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/)

![git](https://user-images.githubusercontent.com/40712459/85135052-5bb7bb80-b235-11ea-80c3-01f555ec9ee6.gif)

### Happy coding

2020-06-19 13:01 UTC, shloch commented on src/logic/operate.js
> +        return a.div(b).toString();
dont forget to manage DIVISION by ZERO on `milestone5`, else it will generate an error

2020-06-19 13:56 UTC, closed without merging

2020-06-19 13:57 UTC, IBTechRaj commented
Resolved conflicts in local repo, merged and pushed to github